version: '3'

services:
  web:
    container_name: gift-for-export_web
    image: dvorak-dev/gift-for-export
    build:
      context: .
      dockerfile: docker/production/web/Dockerfile
      args:
        # [Choice] Ruby version: 2, 2.7, 2.7.4
        RUBY_VERSION: 2.7.4
        # [Choice] Node.js version: lts, 16, 14, 12, 10
        NODE_VERSION: "14.19.0-r0"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        UID: 1000
        GID: 1000
    env_file: docker/production/.env
    restart: unless-stopped
    # volumes:
    #   # - web_gems:/usr/local/bundle
    #   - web_log:/usr/local/app/log
    #   # - web_modules:/usr/local/app/node_modules
    #   - web_uploads:/usr/local/app/private/web_uploads
    # command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000