version: '3'

services:
  web:
    container_name: gift.noack.net.ar_web
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      args:
        RUBY_VERSION: '2.6.5'
        BUNDLER_VERSION: '2.1.4'
    environment:
      # - BUNDLE_PATH=/usr/local/bundle
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - SECREY_KEY_BASE=9e803c5c2d3f977ca3bd09220f008ca2e076d28bfe4b09427e212bab0c14942ba26ee6
      - RAILS_SERVE_STATIC_FILES=1
      - RAILS_MASTER_KEY=f220b7bbaa4c2d78f085df26bed03647
      - EDITOR=vi
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.giftforexport-https.redirectscheme.scheme=https
      - traefik.http.routers.giftforexport-http.entrypoints=http
      - traefik.http.routers.giftforexport-http.rule=Host(`gift.noack.net.ar`)
      - traefik.http.routers.giftforexport-http.middlewares=giftforexport-https@docker
      - traefik.http.routers.giftforexport.entrypoints=https
      - traefik.http.routers.giftforexport.rule=Host(`gift.noack.net.ar`)
      - traefik.http.routers.giftforexport.tls=true
      - traefik.http.routers.giftforexport.tls.certresolver=heimdallrResolver
    # volumes:
    #   - .:/app:cached
      # - gems:/usr/local/bundle
    ports:
      - 3000:3000

# volumes:
#   gems:
