version: '3'

services:
  web:
    container_name: gift.noack.net.ar_web
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    restart: unless-stopped
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - SECREY_KEY_BASE=9e803c5c2d3f977ca3bd09220f008ca2e076d28bfe4b09427e212bab0c14942ba26ee6
      - RAILS_SERVE_STATIC_FILES=1
      - RAILS_MASTER_KEY=f220b7bbaa4c2d78f085df26bed03647
      - EDITOR=vi
    ports:
      - 3000:3000
