version: '3.5'

services:
  web:
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.giftforexport-https.redirectscheme.scheme=https
      - traefik.http.routers.giftforexport-http.entrypoints=http
      - traefik.http.routers.giftforexport-http.rule=Host(`gift.noack.net.ar`)
      - traefik.http.routers.giftforexport-http.middlewares=giftforexport-https@docker
      - traefik.http.routers.giftforexport.entrypoints=https
      - traefik.http.routers.giftforexport.rule=Host(`gift.noack.net.ar`)
      - traefik.http.routers.giftforexport.tls=true
      - traefik.http.routers.giftforexport.tls.certresolver=heimdallrResolver
    networks:
      - heimdallr

networks:
  heimdallr:
    external: true