version: '3'

services:
  web:
    container_name: gift.noack.net.ar_web
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: '2.6.5'
        BUNDLER_VERSION: '2.1.4'
        BUNDLE_PATH: '/usr/local/bundle'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: unless-stopped
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - RAILS_ENV=production
      - RACK_ENV=production
      - SECREY_KEY_BASE=9e803c5c2d3f977ca3bd09220f008ca2e076d28bfe4b09427e212bab0c14942ba26ee6
      - RAILS_SERVE_STATIC_FILES=1
      - EDITOR=vi
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.giftforexport-https.redirectscheme.scheme=https
      - traefik.http.routers.giftforexport-http.entrypoints=http
      - traefik.http.routers.giftforexport-http.rule=Host(`gift.noack.net.ar`)
      - traefik.http.routers.giftforexport-http.middlewares=giftforexport-https@docker
      - traefik.http.routers.giftforexport.entrypoints=https
      - traefik.http.routers.giftforexport.rule=Host(`gift.noack.net.ar`)
      - traefik.http.routers.giftforexport.tls=true
      - traefik.http.routers.giftforexport.tls.certresolver=heimdallrResolver
    networks:
      - heimdallr
    volumes:
      - .:/app:cached
      - gems:/usr/local/bundle

networks:
  heimdallr:
    external: true

volumes:
  gems:
