name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"
  VERSION: "1.1.3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      # run: docker build . --file docker/production/web/Dockerfile --tag $IMAGE_NAME:$(date +%s)
      # IMAGE_ID=$REGISTRY/$IMAGE_NAME:${{ github.run_id }}
      # run: docker build . --file docker/production/web/Dockerfile --tag $IMAGE_NAME:${{ github.run_id }}
      run: docker build --file docker/production/web/Dockerfile -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .

    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image to GitHub Container Registry
      run: |
        IMAGE_ID=$REGISTRY/$IMAGE_NAME:${{ github.run_id }}
        docker push $IMAGE_NAME --all-tags
