name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"
  VERSION: "1.1.3"

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Build the Docker image
  #     run: docker build --file docker/production/web/Dockerfile -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .

  #   - name: Log into GitHub Container Registry
  #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

  #   - name: Push image to GitHub Container Registry
  #     run: |
  #       IMAGE_ID=$REGISTRY/$IMAGE_NAME:${{ github.run_id }}
  #       docker push $IMAGE_NAME --all-tags

  # https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

  build-rpi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7
        file: docker/production/web/Dockerfile
        # tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        push: true


